### ISSUE TITLE
Write shell script to download and unzip data

### ISSUE THREAD

**Issue by korenmiklos** [ceumicrodata/respect-trade-similarity#2]
- Using the URL `https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&downfile=comext%2FCOMEXT_DATA%2FPRODUCTS%2Ffull201852.7z`, write a bash script for a for loop to download data with `wget`.
- Make sure to save these zip files in a subfolder (say, `raw_data`). 
- Unzip them with 7z (you can install with `sudo apt-get install p7zip-full`).
- Edit .gitignore to make sure git does not version these large files.

**Comment by gaborberei** [comment]
OK, ready with EUROSTAT databases, what else we need?
